### ISSUE TITLE
[Travis] Add PR comment with a link to Travis Angular page automerge build

### ISSUE THREAD

**Issue by AkioFaris** [jdi-testing/test-site#15]
When new PR in https://github.com/jdi-testing/test-site project is merged into master, Travis starts a new build that should automerge new build of Angular page to [jgi-light's gh-pages branch](https://github.com/jdi-testing/jdi-light/tree/gh-pages/angular). The description of this process can be found here: https://github.com/jdi-testing/test-site/wiki/Angular-setup-and-build-process

The task is to post a link to this build as a new comment to the related pull request. For example, https://github.com/jdi-testing/test-site/pull/18 pull request started a build https://travis-ci.com/github/jdi-testing/test-site/builds/173013394. We want this automerge build to post comment with this build link (at the start of the build) into [PR](https://github.com/jdi-testing/test-site/pull/18)'s comment section. 

[These script](https://github.com/jdi-testing/jdi-light/blob/master/reports.sh) has the example (sendComment function) of how to post comments to github from Travis build.

**Comment by yakovzaborov** [comment]
Unfortunately, I did not complete the task. In the task, we should -  first get the ID of the last  PR [Tgavis automerge from test-site], then send a comment on it as it was done in the report.sh JDI-Light.
But. It was not possible to get the PR ID using git ls-remote, it returns only the first 1000 PRs. There are more than 1000 there.
Maybe we need a different approach, for example, try inserting a badge with a link to the desired build in Travis

**Comment by AlexeyGirin** [comment]
Not actual any more since we migrated to GitHub Actions
